run: myC_hw2.g
	java -cp ./antlr-3.5.2-complete.jar org.antlr.Tool myC_hw2.g
	javac -cp ./antlr-3.5.2-complete.jar *.java

clean:
	rm -rf *.class
	rm -rf *.tokens
	rm -rf myC_hw2Lexer.java myC_hw2Parser.java
